name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - anaconda-anon-usage=0.7.3
  - anaconda-auth=0.10.0
  - anaconda-cli-base=0.5.4
  - anaconda_powershell_prompt=1.1.0
  - anaconda_prompt=1.1.0
  - annotated-types=0.6.0
  - archspec=0.2.5
  - blas=1.0
  - boltons=25.0.0
  - bottleneck=1.4.2
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.3.2
  - click=8.1.8
  - colorama=0.4.6
  - conda=25.9.1
  - conda-anaconda-telemetry=0.3.0
  - conda-anaconda-tos=0.2.2
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=25.4.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.12.0
  - cpp-expected=1.1.0
  - cryptography=46.0.2
  - distro=1.9.0
  - expat=2.7.1
  - fmt=11.2.0
  - frozendict=2.4.2
  - icc_rt=2022.1.0
  - idna=3.7
  - intel-openmp=2025.0.0
  - jaraco.classes=3.4.0
  - jaraco.context=6.0.0
  - jaraco.functools=4.1.0
  - joblib=1.5.2
  - jpype1=1.6.0
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - keyring=25.6.0
  - libarchive=3.8.2
  - libcurl=8.15.0
  - libffi=3.4.4
  - libiconv=1.16
  - libmamba=2.3.2
  - libmambapy=2.3.2
  - libmpdec=4.0.0
  - libsolv=0.7.30
  - libssh2=1.11.1
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markdown-it-py=4.0.0
  - mdurl=0.1.2
  - menuinst=2.3.1
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - more-itertools=10.8.0
  - nlohmann_json=3.11.2
  - numexpr=2.14.1
  - numpy=2.3.4
  - numpy-base=2.3.4
  - openssl=3.5.4
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.46
  - pip=25.2
  - pkce=1.0.3
  - platformdirs=4.3.7
  - pluggy=1.5.0
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.23
  - pydantic=2.12.2
  - pydantic-core=2.41.4
  - pydantic-settings=2.10.1
  - pygments=2.19.1
  - pyjwt=2.10.1
  - pysocks=1.7.1
  - python=3.13.9
  - python-dateutil=2.9.0post0
  - python-dotenv=1.1.0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - pywin32-ctypes=0.2.2
  - readchar=4.2.1
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.5
  - rich=14.2.0
  - ruamel.yaml=0.18.10
  - ruamel.yaml.clib=0.2.12
  - scikit-learn=1.7.1
  - scipy=1.16.3
  - semver=3.0.2
  - setuptools=80.9.0
  - shellingham=1.5.0
  - simdjson=3.10.1
  - six=1.17.0
  - sqlite=3.50.2
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - threadpoolctl=3.5.0
  - tk=8.6.15
  - tomli=2.2.1
  - tqdm=4.67.1
  - truststore=0.10.1
  - typer=0.17.4
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - yaml-cpp=0.8.0
  - zlib=1.3.1
  - zstandard=0.24.0
  - zstd=1.5.7
  - pip:
      - konlpy==0.6.0
      - lxml==6.0.2
